'use client'
import Loading from "@/components/Loading"
import { useAuth } from "@clerk/nextjs"
import axios from "axios"
import { 
    CircleDollarSignIcon, 
    ShoppingBasketIcon, 
    TruckIcon, 
    ClockIcon,
    DownloadIcon,
    TrendingUp,
    Package // New Icon for Total Orders
} from "lucide-react"
import { useRouter } from "next/navigation"
import { useEffect, useState } from "react"
import toast from "react-hot-toast"
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import {
  LineChart, 
  Line,      
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from 'recharts'

export default function Dashboard() {

    // AUTHENTICATION & CONFIG
    const { getToken } = useAuth()
    const currency = process.env.NEXT_PUBLIC_CURRENCY_SYMBOL || 'Rs'
    const router = useRouter() 

    // STATE MANAGEMENT
    const [loading, setLoading] = useState(true)
    
    const [dashboardData, setDashboardData] = useState({
        totalProducts: 0,
        totalEarnings: 0,
        totalOrders: 0, // Changed from totalGoals
        ordersDelivered: 0,
        pendingDeliveries: 0,
        allOrders: [] 
    })
    const [chartData, setChartData] = useState([])

    /**
     * PROCESS CHART DATA
     */
    const processChartData = (orders = []) => {
        const data = [];
        const today = new Date();
        
        for (let i = 6; i >= 0; i--) {
            const d = new Date();
            d.setDate(today.getDate() - i);
            
            const comparisonDate = d.toLocaleDateString();
            const label = d.toLocaleDateString('en-US', { weekday: 'short' }); 
            
            const daysOrders = orders.filter(o => {
                if (!o.createdAt) return false;
                const orderDate = new Date(o.createdAt).toLocaleDateString();
                return orderDate === comparisonDate;
            });

            const dailyRevenue = daysOrders.reduce((acc, curr) => acc + (Number(curr.total) || 0), 0);
            
            data.push({
                name: label,
                revenue: dailyRevenue
            });
        }
        return data;
    }

    // API INTEGRATION
    const fetchDashboardData = async () => {
        try {
            const token = await getToken()
            
            const { data } = await axios.get('/api/store/dashboard', {
                headers: { Authorization: `Bearer ${token}` }
            })
            
            const safeData = {
                totalProducts: Number(data.dashboardData.totalProducts) || 0,
                totalEarnings: Number(data.dashboardData.totalEarnings) || 0,
                totalOrders: Number(data.dashboardData.totalOrders) || 0, // ✅ Map Total Orders
                ordersDelivered: Number(data.dashboardData.ordersDelivered) || 0,
                pendingDeliveries: Number(data.dashboardData.pendingDeliveries) || 0,
                allOrders: data.dashboardData.allOrders || [] 
            }

            setDashboardData(safeData)
            setChartData(processChartData(safeData.allOrders))

        } catch (error) {
            console.error(error)
            toast.error("Failed to load dashboard data.")
        } finally {
            setLoading(false)
        }
    }

    const GenerateReport = () => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const today = new Date();
        const brandColor = [30, 41, 59];

        doc.setFillColor(...brandColor);
        doc.rect(0, 0, pageWidth, 40, 'F');

        doc.setFontSize(24);
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.text("DREAMSAVER", 14, 20);
        
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text("Store Performance Audit Report", 14, 28);

        doc.setFontSize(10);
        doc.text(`Report ID: ${Date.now()}`, pageWidth - 14, 18, { align: 'right' });
        doc.text(`Date: ${today.toLocaleDateString()}`, pageWidth - 14, 24, { align: 'right' });
        doc.text(`Generated By: Store Manager`, pageWidth - 14, 30, { align: 'right' });

        let yPos = 55;
        
        doc.setFontSize(14);
        doc.setTextColor(...brandColor);
        doc.text("1. Performance Overview", 14, yPos);
        
        const cardWidth = 45;
        const cardHeight = 25;
        const gap = 5;
        const startX = 14;
        yPos += 5;

        const stats = [
            { label: "Total Earnings", value: `${currency}${dashboardData.totalEarnings.toLocaleString()}` },
            { label: "Products", value: dashboardData.totalProducts.toString() },
            { label: "Total Orders", value: dashboardData.totalOrders.toString() },
            { label: "Delivered", value: dashboardData.ordersDelivered.toString() }
        ];

        stats.forEach((stat, index) => {
            const x = startX + (index * (cardWidth + gap));
            doc.setFillColor(248, 250, 252); 
            doc.setDrawColor(226, 232, 240); 
            doc.roundedRect(x, yPos, cardWidth, cardHeight, 3, 3, 'FD'); 

            doc.setFontSize(9);
            doc.setTextColor(100, 116, 139);
            doc.text(stat.label, x + 5, yPos + 8);

            doc.setFontSize(14);
            doc.setTextColor(...brandColor);
            doc.setFont("helvetica", "bold");
            doc.text(stat.value, x + 5, yPos + 18);
        });

        yPos += cardHeight + 15;
        doc.setFontSize(14);
        doc.setTextColor(...brandColor);
        doc.text("2. Operational Metrics", 14, yPos);

        yPos += 5;
        doc.setFontSize(10);
        doc.setTextColor(50);
        const healthText = `Pending Deliveries: ${dashboardData.pendingDeliveries} | Delivery Completion Rate: ${dashboardData.ordersDelivered > 0 ? ((dashboardData.ordersDelivered / (dashboardData.ordersDelivered + dashboardData.pendingDeliveries)) * 100).toFixed(1) + '%' : 'N/A'}`;
        doc.text(healthText, 14, yPos + 5);

        yPos += 15;
        doc.setFontSize(14);
        doc.setTextColor(...brandColor);
        doc.setFont("helvetica", "bold");
        doc.text("3. Daily Revenue Breakdown (Last 7 Days)", 14, yPos);

        const auditRows = chartData.length > 0 ? chartData.map(day => [
            day.name,
            `${currency}${day.revenue.toLocaleString()}`,
            day.revenue > 0 ? 'Active' : 'No Sales'
        ]) : [['-', '-', '-']];

        autoTable(doc, {
            startY: yPos + 5,
            head: [['Day', 'Revenue', 'Status']],
            body: auditRows,
            theme: 'grid',
            headStyles: { 
                fillColor: brandColor, 
                textColor: 255, 
                fontSize: 10,
                fontStyle: 'bold'
            },
            bodyStyles: { 
                fontSize: 9, 
                cellPadding: 4,
                textColor: 50
            },
            alternateRowStyles: { 
                fillColor: [241, 245, 249] 
            },
            columnStyles: {
                0: { fontStyle: 'bold' },
                1: { halign: 'right' }
            },
            didDrawPage: function (data) {
                doc.setFontSize(8);
                doc.setTextColor(150);
                const footerText = `DreamSaver Store Audit Report - Page ${doc.internal.getNumberOfPages()}`;
                doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });
            }
        });

        doc.save(`DreamSaver_Store_Report_${today.toISOString().split('T')[0]}.pdf`);
    }

    useEffect(() => {
        fetchDashboardData()
    }, [])

  
    const dashboardCardsData = [
        { 
            title: 'Total Earnings', 
            value: currency + dashboardData.totalEarnings.toLocaleString(), 
            icon: CircleDollarSignIcon,
            gradient: 'from-emerald-500 to-green-600',
            bgLight: 'bg-emerald-50',
            textColor: 'text-emerald-600'
        },
        { 
            title: 'Total Products', 
            value: dashboardData.totalProducts, 
            icon: ShoppingBasketIcon,
            gradient: 'from-blue-500 to-indigo-600',
            bgLight: 'bg-blue-50',
            textColor: 'text-blue-600'
        },
        { 
            // ✅ CHANGED: Total Orders Card
            title: 'Total Orders', 
            value: dashboardData.totalOrders, 
            icon: Package, // New Icon
            gradient: 'from-violet-500 to-purple-600',
            bgLight: 'bg-violet-50',
            textColor: 'text-violet-600'
        },
        { 
            title: 'Orders Delivered', 
            value: dashboardData.ordersDelivered, 
            icon: TruckIcon,
            gradient: 'from-cyan-500 to-teal-600',
            bgLight: 'bg-cyan-50',
            textColor: 'text-cyan-600'
        },
        { 
            title: 'Pending Deliveries', 
            value: dashboardData.pendingDeliveries, 
            icon: ClockIcon,
            gradient: 'from-amber-400 to-orange-500',
            bgLight: 'bg-amber-50',
            textColor: 'text-amber-600'
        },
    ]

    if (loading) return (
        <div className="min-h-[70vh] flex items-center justify-center bg-slate-50/50">
            <div className="text-center space-y-3">
                <Loading />
                <p className="text-slate-500 animate-pulse">Syncing store data...</p>
            </div>
        </div>
    )

    return (
        <div className="min-h-screen bg-slate-50/30 p-4 lg:p-8">
            <div className="max-w-7xl mx-auto space-y-8">
                
                {/* Header Section */}
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-slate-200 pb-6">
                    <div>
                        <h1 className="text-3xl lg:text-4xl font-extrabold text-slate-900 tracking-tight">
                            Store <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-violet-600">Overview</span>
                        </h1>
                        <p className="text-slate-500 mt-2 text-base lg:text-lg">
                            Track your performance, goals, and delivery status.
                        </p>
                    </div>

                    <div className="flex items-center gap-3">
                        <button 
                            onClick={GenerateReport}
                            className="group flex items-center gap-2 bg-slate-900 text-white px-5 py-2.5 rounded-full shadow-lg shadow-slate-900/20 hover:bg-slate-800 hover:scale-105 active:scale-95 transition-all duration-200"
                        >
                            <DownloadIcon size={18} className="group-hover:-translate-y-0.5 transition-transform" />
                            <span className="font-medium text-sm">Download Report</span>
                        </button>
                    </div>
                </div>

                {/* Stats Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                    {dashboardCardsData.map((card, index) => (
                        <div 
                            key={index} 
                            className="relative overflow-hidden bg-white rounded-3xl p-6 border border-slate-100 shadow-sm hover:shadow-xl hover:shadow-slate-200/50 transition-all duration-300 hover:-translate-y-1 group"
                        >
                            <div className={`absolute top-0 right-0 w-32 h-32 bg-gradient-to-br ${card.gradient} opacity-5 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-150 duration-500`}></div>

                            <div className="relative z-10 flex items-start justify-between">
                                <div className="space-y-4">
                                    <div className={`w-12 h-12 rounded-2xl ${card.bgLight} ${card.textColor} flex items-center justify-center`}>
                                        <card.icon size={24} />
                                    </div>
                                    <div>
                                        <p className="text-slate-500 text-sm font-semibold uppercase tracking-wider">{card.title}</p>
                                        <h3 className="text-3xl font-bold text-slate-900 mt-1">{card.value}</h3>
                                    </div>
                                </div>
                            </div>
                            <div className={`absolute bottom-0 left-0 w-full h-1.5 bg-gradient-to-r ${card.gradient} opacity-80`}></div>
                        </div>
                    ))}
                </div>

                {/* --- Chart Section --- */}
                <div className="w-full bg-white rounded-3xl p-6 border border-slate-100 shadow-sm">
                    <div className="flex items-center justify-between mb-6">
                        <div>
                            <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                                <TrendingUp className="text-blue-600" size={24} />
                                Revenue Analytics
                            </h2>
                            <p className="text-sm text-slate-500 mt-1">Daily earnings for the last 7 days</p>
                        </div>
                    </div>

                    <div className="h-[350px] w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <LineChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                                <XAxis 
                                    dataKey="name" 
                                    axisLine={false} 
                                    tickLine={false} 
                                    tick={{fill: '#64748b', fontSize: 12}} 
                                    dy={10}
                                />
                                <YAxis 
                                    axisLine={false} 
                                    tickLine={false} 
                                    tick={{fill: '#64748b', fontSize: 12}} 
                                    tickFormatter={(value) => `${currency}${value}`}
                                />
                                <Tooltip 
                                    contentStyle={{ backgroundColor: '#fff', borderRadius: '12px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                                    itemStyle={{ color: '#1e293b', fontWeight: 600 }}
                                    formatter={(value) => [`${currency}${value}`, "Revenue"]}
                                />
                                <Line 
                                    type="monotone" 
                                    dataKey="revenue" 
                                    stroke="#4f46e5" 
                                    strokeWidth={3} 
                                    dot={{ r: 4, fill: "#4f46e5", strokeWidth: 2, stroke: "#fff" }}
                                    activeDot={{ r: 6, strokeWidth: 0, fill: "#4f46e5" }}
                                />
                            </LineChart>
                        </ResponsiveContainer>
                    </div>
                </div>

            </div>
        </div>
    )
}